#cloud-config

## Set your hostname here, the manage_etc_hosts will update the hosts file entries as well
hostname: k8s-master-01
manage_etc_hosts: true

## Set the locale of the system
locale: 'en_AU.UTF-8'

## Set the timezone
## Value of 'timezone' must exist in /usr/share/zoneinfo
timezone: 'Europe/London'

apt_preserve_sources_list: true
apt_update: true
apt_upgrade: true

users:
  - name: timi
    primary-group: users
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: users
    ssh_import_id: None
    ## To enable SSH password log in
    ## mkpasswd --method=SHA-512 --rounds=4096
    # passwd: ""
    # lock_passwd: false
    # ssh_pwauth: true
    lock_passwd: true
    ssh_pwauth: false
    ssh_authorized_keys:
      - 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCo5pLMQUVHoHRG0oEbUJGqbp3Ry5huqvSofXm60+aZ6gJ3H/NcQc69nJwgp08kCFaoEpDi+/RHW4wTgy5kvV8HwaC+gFEnwwUQgFcoU7NcZ3BjMk15wRlrQCxU1YCWKHeesoHMM39eHpCaKVc+PMTjeO3xDtG4pAxvlSAna+vWuAmyg1lusJkDNtwGGyNKyFPw/0uTX1CNOdOLc27VopWVUfONRiXlVq7xpiRSmZbmHRB2TqiX31DkQx9n+iOnJm2cNf6ztMLZikegRkH/TmDeNN3x34ahqG+v/yRL7sqodUICeuPYE0jf6ecQnax5Hlg4mRzVDRcOa20wPkTSbIsnZ1StkwPFt7NIFglyo2mtMAadqjX3QOLQC+T5he12zKltAFMMFYBan29t/NeuoRos00vdqN0g8DwgJLu8zLuGb7jzwW94h7RuLNuPLMMynloBCNJ2WsPbwxPc/HYPaklL5bAUgEmlXELVuj38WxDBDhfJI1sXgJjaCE2dRhsiXl9tCG5Ru+gs31rDw8dt4FYwxQvtKXmEeZA8C+zu5upaW9g4swIoV5gBzG7R8lfmBRdwgS1UpgVXbMIZG3cayjEsOKtZxfWfdxHdXjzy4BkrSNwJo38nWBEPuRa29HDmZMyWrafWI2bokV44YJSiFy9+y5HXFcf47LJWPxvXIes6pQ== Edun@Eduns-MacBook-Air.local'
write_files:
  - path: /etc/netplan/50-cloud-init.yaml
    permissions: '0644'
    content: |
      network:
        version: 2
        ethernets:
          eth0:
            addresses:
              - 192.168.0.121/24
            gateway4: 192.168.0.1
            nameservers:
              addresses:
                - 1.1.1.1
                - 8.8.8.8
    ## To enable WiFi network connection
    ## Note: IP allocation is dynamic and won't match the defined state as in eth0.
    ##       This will require manually configuring the Ansible inventory file with
    ##       the assigned IP values.
    #     wifis:
    #       wlan0:
    #         optional: true
    #         dhcp4: true
    #         access-points:
    #           'YOUR-SSID-NAME':
    #             password: 'YOUR-NETWORK-PASSWORD'

runcmd:
  - [sudo, netplan, apply]
  - [
      sudo,
      sed,
      -i,
      's/PasswordAuthentication no/PasswordAuthentication yes/g',
      /etc/ssh/sshd_config,
    ]
  - [sudo, systemctl, restart, sshd]
